// Generated by dia2code
#ifndef STATE__CHARACTERS__H
#define STATE__CHARACTERS__H

#include <string>

namespace state {
  class Statistics;
  class Position;
}

#include "Statistics.h"
#include "Position.h"

namespace state {

  /// class Characters - 
  class Characters {
    // Associations
    // Attributes
  public:
    std::string name;
    Statistics stats;
    Position position;
  private:
    unsigned int number_of_attacks;
    unsigned int attack_cost[MAX_NB_ATTACK];
    unsigned int attack_damage[MAX_NB_ATTACK];
    void* attack_field_of_action[MAX_NB_ATTACK];
    // Operations
  public:
    Characters ();
    Characters (Statistics stats);
    Characters (std::string name);
    void addAttack (unsigned int attack_cost, unsigned int attack_damage, void* attack_field_of_action);
    unsigned int get_attack_cost (unsigned int numero_attack);
    unsigned int get_attack_damage (unsigned int numero_attack);
    void* get_attack_field_of_action (unsigned int numero_attack);
    unsigned int get_number_of_attacks ();
    // Setters and Getters
  };

};

#endif
