// Generated by dia2code
#ifndef STATE__GAMESTATE__H
#define STATE__GAMESTATE__H


namespace state {
  class Map;
  class Player;
  class Characters;
}

#include "StateID.h"
#include "Map.h"

namespace state {

  /// class GameState - 
  class GameState {
    // Associations
    // Attributes
  public:
    StateID state;
    Map map;
    int current_player;
    Player * players[10];
    Characters * characters[10];
    // Operations
  public:
    GameState ();
    void new_map (Map carte);
    // Setters and Getters
  };

};

#endif
