// Generated by dia2code
#ifndef STATE__GAMESTATE__H
#define STATE__GAMESTATE__H

#include <vector>
#include <memory>
#include <string>

namespace state {
  class Map;
  class Player;
}

#include "StateID.h"
#include "Map.h"
#include "Player.h"

namespace state {

  /// class GameState - 
  class GameState {
    // Associations
    // Attributes
  public:
    StateID state;
    Map map;
    Player current_player;
    std::vector<std::unique_ptr<Player>> players;
    // Operations
  public:
    GameState ();
    void new_map ();
    void new_player (const std::string name);
    int get_number_of_player ();
    // Setters and Getters
  };

};

#endif
