// Generated by dia2code
#ifndef STATE__MAP__H
#define STATE__MAP__H

#include <vector>

namespace state {

  /// class Map - 
  class Map {
    // Attributes
  private:
    int width;
    int height;
    std::vector<std::vector<int>> mask;
    // Operations
  public:
    void create_mask ();
    void set_screen_dimensions ();
    void get_dimensions (int& width, int& height) const;
    void set_dimensions (const int width, const int height);
    const std::vector<std::vector<int>>& get_mask () const;
    void update_mask (int* mask);
  private:
    void fill_mask_with_x (auto& mask, const int x);
    void affiche (const auto& mask);
    void puts_zero (auto& mask, const int x, const int y);
    int* new_line_index (int* x, const int& height);
    // Setters and Getters
  };

};

#endif
