// Generated by dia2code
#ifndef STATE__MAP__H
#define STATE__MAP__H


namespace state {
  class GameState;
}

#include "GameState.h"

namespace state {

  /// class Map - 
  class Map {
    // Associations
    // Attributes
  public:
    int width;
    int height;
    int mask[10][10];
    // Operations
  public:
    void get_screen_dimensions ();
    void create_mask (int width, int height);
    void update_mask (int* mask);
    // Setters and Getters
  };

};

#endif
