// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H


namespace state {
  class Characters;
  class GameState;
}

#include "Characters.h"
#include "GameState.h"

namespace state {

  /// class Player - 
  class Player {
    // Associations
    // Attributes
  public:
    int number_of_characters;
    Characters current_character;
    Characters characters[];
    // Operations
  public:
    Player ();
    void add_character (Characters new_character);
    void select_character ();
    // Setters and Getters
  };

};

#endif
