// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <string>
#include <vector>
#include <memory>

namespace state {
  class Characters;
}

#include "Characters.h"

namespace state {

  /// class Player - 
  class Player {
    // Associations
    // Attributes
  public:
    std::string name;
    Characters current_character;
    std::vector<std::unique_ptr<Characters>> characters;
  private:
    unsigned int number_of_characters;
    // Operations
  public:
    Player ();
    Player (std::string name);
    void add_character (Characters new_character);
    void select_character (Characters character);
    unsigned int get_number_of_characters ();
    void set_number_of_characters (unsigned int number);
    // Setters and Getters
  };

};

#endif
