// Generated by dia2code
#ifndef STATE__POSITION__H
#define STATE__POSITION__H


namespace state {

  /// class Position - 
  class Position {
    // Attributes
  public:
    int x;
    int y;
    // Setters and Getters
  };

};

#endif
