// Generated by dia2code
#ifndef STATE__POSITION__H
#define STATE__POSITION__H


namespace state {

  /// class Position - 
  class Position {
    // Attributes
  private:
    unsigned int x;
    unsigned int y;
    // Operations
  public:
    void setPosition (const unsigned int x, const unsigned int y);
    unsigned int getPositionX ();
    unsigned int getPositionY ();
    // Setters and Getters
  };

};

#endif
