// Generated by dia2code
#ifndef STATE__STATISTICS__H
#define STATE__STATISTICS__H


namespace state {

  /// class Statistics - 
  class Statistics {
    // Attributes
  public:
    int life_point;
    int attack_point;
    int move_point;
    // Operations
  public:
    Statistics (int vie = 100, int attaque = 10, int deplacement = 10);
    void Get_life_points ();
    void Get_attack_points ();
    void Get_move_points ();
    void Set_statistiques (int life_point, int attack_point, int move_point);
    // Setters and Getters
  };

};

#endif
