// Generated by dia2code
#ifndef STATE__STATEID__H
#define STATE__STATEID__H


namespace state {

  enum StateID {
    not_started     = 0,
    team_select     = 1,
    init     = 2,
    started     = 3,
    paused     = 4,
    end     = 5
  };

};

#endif
