// Generated by dia2code
#ifndef STATE__STATISTICS__H
#define STATE__STATISTICS__H


namespace state {

  /// class Statistics - 
  class Statistics {
    // Attributes
  private:
    unsigned int life_point;
    unsigned int attack_point;
    unsigned int move_point;
    // Operations
  public:
    Statistics (int vie = 100, int attaque = 10, int deplacement = 10);
    unsigned int Get_life_points ();
    unsigned int Get_attack_points ();
    unsigned int Get_move_points ();
    void Set_statistiques (int vie, int attaque, int deplacement);
    // Setters and Getters
  };

};

#endif
