// Generated by dia2code
#ifndef STATE__UNIQUE_VECTOR__H
#define STATE__UNIQUE_VECTOR__H

#include <vector>
#include <memory>


  /// class Unique_vector - 
template <class T>
class Unique_vector{
    
    public:
    std::vector<std::unique_ptr<T>> vec;
    T* operator[](int i){
        
        return vec[i].get();
    }
    
    void push_back(std::unique_ptr<T>& p){
        vec.push_back(move(p));
    }
};


#endif
