// Generated by dia2code
#ifndef RENDER__BACKGROUND__H
#define RENDER__BACKGROUND__H


namespace state {
  class GameState;
  class Map;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/Map.h"

namespace render {

  /// class Background - 
  class Background : public render::Layer {
    // Associations
    // Attributes
  protected:
    const state::GameState& state;
    const state::Map& map;
    // Operations
  public:
    Background (const state::GameState& state, const state::Map& map);
    void make_mask ();
    void update ();
    // Setters and Getters
    const state::GameState& getState() const;
    const state::Map& getMap() const;
  };

};

#endif
