// Generated by dia2code
#ifndef RENDER__CHARACTER__H
#define RENDER__CHARACTER__H

#include <vector>
#include <memory>

namespace state {
  class GameState;
  class Characters;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/Characters.h"

namespace render {

  /// class Character - 
  class Character : public render::Layer {
    // Associations
    // Attributes
  public:
    const state::GameState& state;
    std::vector<std::shared_ptr<state::Characters>> characters;
    state::Characters* dia_issue2;
    // Operations
  public:
    Character (const state::GameState& state);
    void fill_characters_list ( );
    // Setters and Getters
  };

};

#endif
