// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <memory>
#include <vector>
#include <SFML/Graphics.hpp>

namespace render {
  class Surface;
  class TileSet;
}

#include "Surface.h"
#include "TileSet.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  protected:
    std::unique_ptr<Surface> surface;
    std::vector<std::shared_ptr<TileSet>> tileset;
    TileSet* dia_issue;
    // Operations
  public:
    Layer ();
    void setSurface (sf::RenderWindow& window);
    void update ();
    // Setters and Getters
    const std::unique_ptr<Surface>& getSurface() const;
    const std::vector<std::shared_ptr<TileSet>>& getTileset() const;
    void setTileset(const std::vector<std::shared_ptr<TileSet>>& tileset);
    const TileSet*& getDia_issue() const;
    void setDia_issue(const TileSet*& dia_issue);
  };

};

#endif
