// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H


namespace state {
  class GameState;
};
namespace render {
  class Background;
  class Character;
};
namespace state {
  class Map;
}

#include "Background.h"
#include "Character.h"
#include "state/GameState.h"

namespace render {

  /// class Scene - 
  class Scene {
    // Associations
    // Attributes
  private:
    const state::GameState& state;
    Background background;
    Character characters;
    // Operations
  public:
    Scene (const state::GameState& state, const state::Map& map);
    void updateScene ();
    void draw ();
    // Setters and Getters
  };

};

#endif
