// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <SFML/Graphics.hpp>

namespace render {
  class Tile;
};
namespace state {
  class Position;
}

#include "state/Position.h"

namespace render {

  /// class Surface - 
  class Surface {
    // Attributes
  private:
    sf::Texture texture;
    sf::Sprite sprite;
    // Operations
  public:
    void loadTexture (sf::Image& image);
    /// to display a whole image
    void setSpriteTexture ();
    void setSpriteTexture (const Tile& rect);
    void setSpriteLocation (state::Position position);
    void draw (sf::RenderWindow& window);
    // Setters and Getters
  };

};

#endif
