// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
  class Surface;
}

#include "Tile.h"
#include "Surface.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Associations
    // Attributes
  protected:
    std::vector<sf::Image> images;
    // Operations
  public:
    TileSet ();
    TileSet (std::string image);
    void setImageFile (std::string name);
    sf::Image& getImageFile (unsigned int i);
    // Setters and Getters
    const std::vector<sf::Image>& getImages() const;
    void setImages(const std::vector<sf::Image>& images);
  };

};

#endif
