// Generated by dia2code
#ifndef RENDER__TILE__H
#define RENDER__TILE__H


namespace render {

  /// class Tile - 
  class Tile {
    // Attributes
  public:
    int x;
    int y;
    int width;
    int height;
    // Operations
  public:
    Tile ();
    Tile (int x, int y, int width, int height);
    // Setters and Getters
  };

};

#endif
