// Generated by dia2code
#ifndef __STATE__H
#define __STATE__H

#include "state/StateID.h"
#include "state/Position.h"
#include "state/Statistics.h"
#include "state/Characters.h"
#include "state/Map.h"
#include "state/Player.h"
#include "state/GameState.h"
#endif
